Rozbudowa narzędzia immudex-import-sshkeys - BT #207

diff --git a/tools/bin/immudex-import-sshkeys b/tools/bin/immudex-import-sshkeys
--- a/tools/bin/immudex-import-sshkeys
+++ b/tools/bin/immudex-import-sshkeys
@@ -1,5 +1,24 @@
 #!/bin/bash
 
+function help() {
+  echo "immudex-import-sshkeys - script for copying ssh keys into user native home directory.";
+  echo "@ 2025 morketsmerke.org";
+  echo;
+  echo "Usage:";
+  echo "$ immudex-import-sshkeys"
+  echo "This comman should be run in other home directory, where ssh keys are stored.";
+  echo;
+  echo "Options:";
+  echo "  --help - print this message.";
+  echo "  --import-hosts - import hostnames and adresses to /etc/host file (sudo required)";
+  echo "  from SSH config file if exist.";
+}
+
+if [ "$1" ] && [ "$1" = "--help" ]; then
+  help;
+  exit 1;
+fi
+
 if $(ls $HOME | grep -q '.*_rsa.*'); then
   if [ -d /home/$USER/.ssh ]; then
     cp -v ~/*_rsa* /home/$USER/.ssh;
@@ -11,5 +30,15 @@ if $(ls $HOME | grep -q '.*_rsa.*'); then
 fi
 if $(ls -w1 $HOME | grep -q '^config$'); then
   cp -v ~/config /home/$USER/.ssh;
+  if [ "$1" ] && [ "$1" = "--import-hosts" ]; then
+    i=1;
+    hostsCount=$(grep -o "Host .*" ~/config | wc -l);
+    while [ $i -le $hostsCount ]; do
+      host=$(grep -o "Host .*" ~/config | sed -n "${i}p" | awk '{printf $2}');
+      hostName=$(grep -o "HostName .*" ~/config | sed -n "${i}p" | awk '{printf $2}');
+      echo -e "${host}\t${hostName}" | sudo tee -a /etc/hosts;
+      i=$(expr $i + 1); 
+    done
+  fi
   chmod 600 /home/$USER/.ssh/config;
 fi
