Aktualizacja, dodano możliwość dopisania changelogu użytkownika do obrazu immudex. Dostosowano addon KVM do wymagań wersji libvirt w Debian 13. Do wszystkich autorskich narzędzi dodano funkcje help oraz version, aby można było wygenerować pliki stron podręcznika man. Narzędzia jak immudex-meteo, immudex-motd, immudex-ytplay oraz immudex-run zostały zredefiniowane. Narzędzie immudex-ytplay zostało przepisane od 0 w języku Python z wykorzystaniem biblioteki youtube-search. Narzędzia obsługują teraz ujednoliconą metodę na przekazywanie opcji (--opcja=wartość). Do immudex-install dodano opcję zmiany wielkości partycji z immudex. Nie ma potrzeby zmian w kodzie narzędzia. Oczyszczono plik bazowy z niepotrzebnych poleceń, usunięto pakiet make a dodano mc oraz minicom. Utworzono nową strukturę katalogą dla narzędzi immudex, zawierającą poza samymi skryptami pliki stron podręcznika oraz pliki dodatkowe wymagane przez narzędzia do działania.

diff --git a/tools/bin/immudex-pl b/tools/bin/immudex-pl
--- a/tools/bin/immudex-pl
+++ b/tools/bin/immudex-pl
@@ -2,33 +2,65 @@
 
 GREEN="\e[32m";
 RED="\e[31m";
+YELLOW="\e[33m";
 ENDCOLOR="\e[0m";
+SYSTEM_CC=$(echo $LANG | cut -c 1-2);
+
+function help() {
+  echo "immudex-pl opening (play) links. Script creates menu from link list, which";
+  echo "can be open via mpv (with yt-dlp hook). Normally links are open as";
+  echo "audio stream. Script work in loop, which means you can change playback";
+  echo "while the current one is still playing. When you need to exit type any letter instead of number.";
+  echo "Script is not only for YouTube Links, it can also open";
+  echo "internet radios or shoutcasts. The link list can be downloaded and does";
+  echo "not need to be stored on the target device. Script will delete the";
+  echo "file at the end of its execution. ";
+  echo;
+  echo "Usage: immudex-pl [--video --format=240p...1080p] [--help] [--version] link-list"; 
+  echo;
+  echo "Options:";
+  echo "  --video --format=240p...1080p   Open link as video.";
+  echo "  --help                        Print this message.";
+  echo "  --version                     Print information about version, author and copyrights.";
+  echo;
+  echo "Files:";
+  echo "  /usr/share/doc/immudex-pl/links.list.example    Example link list file.";
+  echo;
+  echo "Examples:"
+  echo "  immudex-pl ~/radio-links.txt    Open given link list as audio stream.";
+  echo "  immudex-pl --video --format=360p ./yt-links   Open given link list as video in 360p format.";
+  echo;
+  echo "Report bugs to <xf0r3m@gmail.com>";
+}
+
+function version() {
+  echo "immudex-pl 1.0-1";
+  echo;
+  echo "Copyright (C) 2026 morketsmerke.org";
+  echo "This is free software; see the source for copying conditions.  There is NO";
+  echo "warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.";
+  echo;
+  echo "Written by xf0r3m.";
+}
 
 if [ "$1" ] && [ $1 = "--video" ]; then
   video=1;
   shift;
-  if [ $# -gt 1 ]; then format="--ytdl-format=$1"; shift; file=$1;
-  else format="--ytdl-forma=best"; file=$1; fi
+  if $(echo $1 | grep -q '\-\-format'); then
+    format=$(echo $1 | grep -o '[0-9]' | awk '{printf $1}')
+  fi
+  shift; 
+  file=$1;
+elif [ "$1" ] && [ $1 = "--help" ]; then
+  help;
+  exit 0;
+elif [ "$1" ] && [ $1 = "--version" ]; then
+  version;
+  exit 0;
 else
   file=$1;
 fi
 
-function help() {
-  echo "immudex-pl - Play Links. Skrypt to odtwarzania multimediów z listy linków";
-  echo "@ 2023 morketsmerke.org";
-  echo;
-  echo "Opcje:";
-  echo;
-  echo -e "\t--video [format] - możliwość odtwarzania linków jako filmów. Format";
-  echo -e "\tjest opcjonalny, w przypadku jego braku, domyślnym formatem jest";
-  echo -e "\t'best'.";
-  echo;
-  echo "Użycie:";
-  echo -e "\t$ pl [http(s)://adres/lub/]sciezka/do/listy/linkow";
-  echo;
-  echo "Format listy:";
-  echo -e "\tnazwa linku: https://youtube.com/...";
-}
 
 if echo $file | grep -q 'http'; then
   echo -n "Getting link list...";
@@ -49,20 +81,54 @@ if [ "$file" ]; then
   select name in $linkNames; do
     if [ "$MPVPID" ]; then kill $MPVPID; fi
     if [ ! "$name" ]; then break; fi
-    link=$(grep "$name" $file | cut -d ":" -f 2-);
+    link=$(grep "$name" $file | cut -d ":" -f 2-3);
     if [ ! "$link" ]; then
       linkName=$(echo $name | sed 's/_/\ /g');
-      link=$(grep "$linkName" $file | cut -d ":" -f 2-);
+      link=$(grep "$linkName" $file | cut -d ":" -f 2-3);
     fi
     if echo $link | grep -q "youtube"; then
       link=$(echo $link | sed 's/\ //g');
       if [ "$video" ]; then
         #ytplay -v $link -f $format
-        mpv $format ytdl://$link > /dev/null 2>&1 & MPVPID=$!
+        #format="--ytdl-format=$(grep "$link" $file | cut -d ":" -f 4-)";
+        echo "Getting requested video format ID...";
+        video=$(yt-dlp --list-formats $link 2>/dev/null | grep "$format" | sed -n '1p' | awk '{printf $1}')
+        if [ ! "$video" ]; then 
+          echo -e "Getting requested video format ID...[ ${RED}FAILED${ENDCOLOR} ]";
+          exit 1;
+        else
+          echo -e "Getting requested video format ID...[ ${GREEN}OK${ENDCOLOR} ]"; 
+        fi
+
+        echo "Getting appropiate audio format ID for video...";
+        audio=$(yt-dlp --list-formats $link 2>/dev/null | grep 'audio only' | grep "$SYSTEM_CC" | sed -n '1p' | awk '{printf $1}');
+        if [ ! "$audio" ]; then
+          echo -e "Getting audio format based on your locales...[ ${RED}FAILED${ENDCOLOR} ]";
+          echo "Getting high quality audio stream format...";
+          audio=$(yt-dlp --list-formats $link 2>/dev/null | grep 'audio only' | grep "high" | sed -n '1p' | awk '{printf $1}');
+          if [ ! "$audio" ]; then
+            echo -e "No audio stream found...[ ${RED}FAILED${ENDCOLOR} ]";
+            echo -e "There is no separate audio stream...[ ${YELLOW}FINE${ENDCOLOR} ]";
+            #exit 1;
+          else
+            echo -e "Getting high quality audio stream format...[ ${GREEN}OK${ENDCOLOR} ]";
+          fi
+        else
+          echo -e "Getting audio format based on your locales...[ ${GREEN}OK${ENDCOLOR} ]";
+        fi
+        if [ ! "$audio" ]; then
+          fmat="--ytdl-format=${video}";
+        else
+          fmat="--ytdl-format=${video}+${audio}";
+        fi
+        echo "MPV is starting up...";
+        mpv $fmat $link > /dev/null 2>&1 & MPVPID=$!
+
       else
         #ytplay -a $link -f best[height=360]
-        format="--no-video --ytdl-format=best[height=360]"; 
-        mpv $format ytdl://$link > /dev/null 2>&1 & MPVPID=$!
+        format="--no-video"; 
+        echo "MPV is starting up...";
+        mpv $format $link > /dev/null 2>&1 & MPVPID=$!
       fi
     else
       mpv --no-video $link > /tmp/pl.log 2>&1 & MPVPID=$!;
diff --git a/tools/bin/immudex-shoutcasts b/tools/bin/immudex-shoutcasts
--- a/tools/bin/immudex-shoutcasts
+++ b/tools/bin/immudex-shoutcasts
@@ -1,28 +1,162 @@
 #!/bin/bash
 
-echo -n "What are you wanna listen? ";
-read search;
+GREEN="\e[32m";
+RED="\e[31m";
+ENDCOLOR="\e[0m";
+BOLD="\e[1m";
+BOLD_GREEN="\e[1;32m";
+BOLD_YELLOW="\e[1;33m";
+BOLD_BLUE="\e[1;34m";
+
+function help() {
+  echo "immudex-shoutcasts script that search internet radios or shoutcasts in two sources xiph.org icecast";
+  echo "directory and download .m3u file from radio-browser.info based on a space-separated keywords.";
+  echo "Data from radio-browser.info are limited to 30 results.";
+  echo;
+  echo "Usage: immudex-shoutcasts [--source=icecast | radio] [--help] [--version] --keywords=keyword1...keywordN";
+  echo;
+  echo "Options:";
+  echo "  --source=icecast/radio              This parameter specifies source, if we want define a source. It can be omitted, then both sources will be searched.";
+  echo "  --keywords=keyword1...keywordsN   This parameter is required, it pass keywords to search. Keywords are space-separated.";
+  echo "  --help                              Print this message.";
+  echo "  --version                           Print information about version, author and copyrights.";
+  echo;
+  echo "Examples:";
+  echo "  immudex-shoutcasts --keywords=Classic Rock          Script will be search internet radios and shoutcast for 'Classic Rock' keywords";
+  echo "  immudex-shoutcasts --source=radio --keywords=lofi   Script will be search internet radios (because source is given) for 'lofi' keyword";
+  echo;
+  echo "Files:"
+  echo "  /tmp/icecast.idx  Temporary file, store search results from icecast directory for parsing.";
+  echo "  /tmp/radio.idx    Temporary file, downloaded .m3u file from radio-browser.info store search results for parsing.";
+  echo;
+  echo "Report bugs to <xf0r3m@gmail.com>";
+}
+
+function version() {
+  echo "immudex-shoutcasts 1.0";
+  echo;
+  echo "Copyright (C) 2026 morketsmerke.org";
+  echo "This is free software; see the source for copying conditions.  There is NO";
+  echo "warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.";
+  echo;
+  echo "Written by xf0r3m.";
+}
+
 
 function getDataBetweenHtmlMarks() {
   grep "$1" $2 | sed -n "${3}p" | cut -d ">" -f 2 | cut -d "<" -f 1;
 }
-wget http://dir.xiph.org/search?q=$search -O /tmp/shcast_dir.html >> /dev/null 2>&1;
-if [ ! -s /tmp/shcast_dir.html ]; then
-  echo -e "\e[31mThere is no internet connection.\e[0m";
-  exit 1;
-else
-  amountOfStations=$(grep 'card-title' /tmp/shcast_dir.html | wc -l);
+
+function listOfStations() {
+  query=$1;
+  src=$2;
+  
+  case $src in
+    "icecast") wget http://dir.xiph.org/search?q=$query -O /tmp/icecast.idx >> /dev/null 2>&1;
+                file="/tmp/icecast.idx";;
+    "radio") wget "https://de1.api.radio-browser.info/m3u/stations/search?limit=30&name=${query}&hidebroken=true&order=clickcount&reverse=true" -O /tmp/radio.idx >> /dev/null 2>&1;
+              file="/tmp/radio.idx";
+              dos2unix $file;
+  esac
+    
+  if [ ! -f $file ]; then
+    echo -e "${RED}There is no internet connection or sources are currently";
+    echo -e "unavailable.${ENDCOLOR}";
+    exit 1;
+  fi
+
+  case $src in
+    "icecast") amountOfStations=$(grep 'card-title' $file | wc -l);;
+    "radio") amountOfStations=$(grep '#EXTINF' $file | wc -l);;
+  esac
+
+  case $src in
+    "icecast") echo -e "${BOLD}Icecast directory:${ENDCOLOR}";;
+    "radio") echo -e "${BOLD}radio-browser.info:${ENDCOLOR}";;
+  esac
+
   i=1;
   while [ $i -le $amountOfStations ]; do
-    stationName=$(getDataBetweenHtmlMarks 'card-title' /tmp/shcast_dir.html ${i});
-    whatIsPlaying=$(getDataBetweenHtmlMarks 'card-subtitle' /tmp/shcast_dir.html ${i});
-    echo -e "${i}. \e[33m${stationName}\e[0m";
-    echo -e "   \e[32m${whatIsPlaying}\e[0m";
-    i=$((i + 1));
+    case $src in
+      "icecast") stationName=$(getDataBetweenHtmlMarks 'card-title' $file $i);;
+      "radio") stationName=$(grep '#EXTINF' $file | sed -n "${i}p" | cut -d "," -f 2-);;
+    esac
+    if [ "$src" = "icecast" ]; then
+      whatIsPlayingNow=$(getDataBetweenHtmlMarks 'card-subtitle' $file $i);
+    fi
+    case $src in
+      "icecast") link=$(grep 'Play' $file | sed -n "${i}p" | cut -d '"' -f 2);;
+      "radio") link=$(grep '://' $file | sed -n "${i}p");;
+    esac
+    echo -e "${BOLD}${i}.${ENDCOLOR} ${BOLD_YELLOW}${stationName}${ENDCOLOR}";
+    if [ "$whatIsPlayingNow" ]; then
+      echo -e "\t${BOLD}Now playing:${ENDCOLOR} ${BOLD_BLUE}${whatIsPlayingNow}${ENDCOLOR}";
+      unset whatIsPlayingNow;
+    fi
+    echo -e "\t${BOLD}Link:${ENDCOLOR} ${BOLD_GREEN}${link}${ENDCOLOR}";
+    i=$(expr $i + 1);
   done
-  echo -n "Pick a one: ";
-  read numberOfStation;
-  echo $(grep 'Play' /tmp/shcast_dir.html | sed -n "${numberOfStation}p" | cut -d '"' -f 2) | xclip -selection c;
-  echo "Station URL was copied to clipboard";
-  
+  unset i;
+  echo;
+}
+
+if [ "$1" ]; then
+
+  if [ "$1" ] && [ "$1" = "--help" ]; then
+    help;
+    exit 0;
+  elif [ "$1" ] && [ "$1" = "--version" ]; then
+    version;
+    exit 0;
+  fi
+
+  option=$(echo $1 | cut -d '=' -f 1);
+  if [ "$option" = "--source" ]; then
+    src=$(echo $1 | cut -d '=' -f 2);
+    search=$(echo $* | cut -d '=' -f 3-);
+  elif [ "$option" = "--keywords" ]; then
+    search=$(echo $* | cut -d "=" -f 2-);
+  fi
+else
+  help;
+  exit 1;
+fi
+
+if [ "$src" ]; then
+  listOfStations "$search" $src;
+  if [ "$src" = "icecast" ]; then
+    file="/tmp/icecast.idx";
+  else
+    file="/tmp/radio.idx";
+  fi
+else
+  listOfStations "$search" 'icecast';
+  listOfStations "$search" 'radio';
+
+  PS3="source? ";
+  select src in 'icecast' 'radio'; do
+    case $src in
+      'icecast') file="/tmp/icecast.idx";;
+      'radio') file="/tmp/radio.idx";;
+      *) exit 0;
+    esac
+    break
+  done
+fi
+
+echo -n "Station? ";
+read station;
+if $(echo $station | grep -q '[0-9]') && [ $station -le 30 ]; then
+  case $file in
+    '/tmp/icecast.idx') link=$(grep 'Play' $file | sed -n "${station}p" | cut -d '"' -f 2);;
+    '/tmp/radio.idx') link=$(grep '://' $file | sed -n "${station}p");;
+  esac
+  case $src in
+      "icecast") stationName=$(getDataBetweenHtmlMarks 'card-title' $file $station);;
+      "radio") stationName=$(grep '#EXTINF' $file | sed -n "${station}p" | cut -d "," -f 2-);;
+  esac
+  echo -e "${BOLD}Station:${ENDCOLOR} ${BOLD_YELLOW}${stationName}${ENDCOLOR}";
+  mpv --no-video $link;
+else
+  exit 0;
 fi
