Zabezpieczenie autorskich narzędzi administracyjnych oraz aktualizacja ich komunikatów pomocy - Zmiana sposobu tworzenia użytkowników na immudex oraz zmiana podejścia do uprawnień cz. 4

diff --git a/tools/sbin/immudex-create-media b/tools/sbin/immudex-create-media
--- a/tools/sbin/immudex-create-media
+++ b/tools/sbin/immudex-create-media
@@ -6,7 +6,8 @@ ENDCOLOR="\e[0m";
 
 function help() {
   echo "immudex-create-media - script used for write iso image to usb drive(mainly)";
-  echo "@ 2023 morketsmerke.org";
+  echo "@ 2024 morketsmerke.org";
+  echo "Superuser (root) privileges are required.";
   echo "Options:";
   echo "  --i386-efi - creating 32-bit EFI usb drive with iso image";
   echo "  (comapatible with immudex only iso images)";
@@ -14,6 +15,12 @@ function help() {
   echo "Usage:";
   echo "  $ immudex-create-media [--i386-efi] [--nuke] <usb_disk> [iso_image]";
 }
+
+if [ $UID -ne 0 ]; then
+  echo "Permission denied!";
+  help;
+  exit 1;
+fi
 
 if [ "$1" ] && [ "$1" = "--i386-efi" ]; then target="i386-efi"; shift; fi
 if [ "$1" ] && [ "$1" = "--nuke" ]; then target="nuke"; shift; fi
diff --git a/tools/sbin/immudex-upgrade b/tools/sbin/immudex-upgrade
--- a/tools/sbin/immudex-upgrade
+++ b/tools/sbin/immudex-upgrade
@@ -12,11 +12,18 @@ root="/run/live/medium";
 
 function help() {
   echo "immudex-upgrade - script for searching upgrades and upgrade immudex";
-  echo "@ 2023 morketsmerke.org";
+  echo "@ 2024 morketsmerke.org";
+  echo "Superuser (root) privileges are required.";
   echo "Options:";
   echo " --check - check there are upgrades for immudex";
   echo " --upgrade - upgrade immudex from given source";
 }
+
+if [ $UID -ne 0 ]; then
+  echo "Permission denied!";
+  help;
+  exit 1;
+fi
 
 if [ "$1" ]; then
   if [ "$1" ] && [ "$1" = "--check" ]; then
