Podział narzędzi autorskich na te niewymagające uprawnień administratora (katalog /usr/local/bin) oraz na te, które tego wymagają (katalog /usr/local/sbin). Wyjątkiem jest immudex-padlock. To narzędzie mimo wymaga uprawnień administratora, pozostaje bez zmian - Zmiana sposobu tworzenia użytkowników na immudex oraz zmiana podejścia do uprawnień cz. 1.

diff --git a/tools/sbin/immudex-crypt b/tools/sbin/immudex-crypt
--- a/tools/sbin/immudex-crypt
+++ b/tools/sbin/immudex-crypt
@@ -4,16 +4,17 @@ function help() {
 
   echo "immudex-crypt - script used for listing, open and close crypt_LUKS ppartitions";
   echo "@ 2023 morketsmerke.org";
+  echo "Superuser (root) privileges are required.";
   echo "Options:";
   echo "  list - displaing list of opened and available crypt_LUKS devices";
   echo "  create - formatting device for crypt_LUKS";
   echo "  open - opening crypt_LUKS device, after this device is ready to mount";
   echo "  close - unmount and closing crypt_LUKS devices";
   echo "Using:";
-  echo "$ immudex-crypt list";
-  echo "$ immudex-crypt create <disk partition>";
-  echo "$ immudex-crypt open <crypt_LUKS device>";
-  echo "$ immudex-crypt close immudex-crypt[0-9] | ic[0-9] | [0-9]";
+  echo "# immudex-crypt list";
+  echo "# immudex-crypt create <disk partition>";
+  echo "# immudex-crypt open <crypt_LUKS device>";
+  echo "# immudex-crypt close immudex-crypt[0-9] | ic[0-9] | [0-9]";
 }
 
 function list() {
@@ -27,7 +28,7 @@ function list() {
 
   if [ "$mapperDeviceList" ]; then
   	  for dmDevice in $mapperDeviceList; do
-		    if sudo cryptsetup status /dev/mapper/${dmDevice} > /dev/null 2>&1; then
+		    if cryptsetup status /dev/mapper/${dmDevice} > /dev/null 2>&1; then
 			    mountPoint=$(df --output=source,target /dev/mapper/${dmDevice} | tail -n 1 | awk '{printf $2}');
           device=$(sudo cryptsetup status /dev/mapper/${dmDevice} | grep "device" | awk '{printf $2}');
     		  if [ "$mountPoint" ] && [ "$mountPoint" != "/dev" ]; then
@@ -69,24 +70,27 @@ function open() {
     else
       index=0;
     fi
-    sudo cryptsetup open $1 immudex-crypt${index};
-    sudo mkdir -p /media/${USER}/immudex-crypt${index};
-    dmDevice=$(ls -l /dev/mapper/immudex-crypt${index} | awk '{printf $10}' | cut -d "/" -f 2);
+    cryptsetup open $1 immudex-crypt${index};
+    mkdir -p /media/${USER}/immudex-crypt${index};
+    # Różnica w reprezentacji czasu modyfikacji miedzy Debian testing a stable i oldstable 
+    #dmDevice=$(ls -l /dev/mapper/immudex-crypt${index} | awk '{printf $10}' | cut -d "/" -f 2);
+    lastField=$(ls -l /dev/mapper/immudex-crypt${index} | grep -o ' ' | wc -l);
+    dmDevice=$(ls -al /dev/mapper/immudex-crypt${index} | cut -d " " -f ${lastField}- | cut -d "/" -f2);
     if ! $(sudo file -s /dev/${dmDevice} | grep -q 'ext4'); then
       echo "Could not determine filesystem of unlocked device.";
       echo -n "Format this device to ext4? (y/n): "
       read format;
       if [ "$format" = "y" ]; then
-        sudo mkfs.ext4 /dev/mapper/immudex-crypt${index};
+        mkfs.ext4 /dev/mapper/immudex-crypt${index};
       else
         echo "Refuse to mount.";
-        sudo cryptsetup close immudex-crypt${index};
+        cryptsetup close immudex-crypt${index};
         exit 1;
       fi
     fi
-    sudo mount /dev/mapper/immudex-crypt${index} /media/${USER}/immudex-crypt${index};
+    mount /dev/mapper/immudex-crypt${index} /media/${USER}/immudex-crypt${index};
     if [ ! -e /ic${index} ]; then
-      sudo ln -s /media/${USER}/immudex-crypt${index} /ic${index};
+      ln -s /media/${USER}/immudex-crypt${index} /ic${index};
     fi
   fi
 
@@ -103,13 +107,13 @@ function close() {
     else
         cryptfsName=$1;
     fi
-    if sudo cryptsetup status /dev/mapper/${cryptfsName} > /dev/null 2>&1; then
+    if cryptsetup status /dev/mapper/${cryptfsName} > /dev/null 2>&1; then
       mountPoint=$(df --output=source,target /dev/mapper/${cryptfsName} | tail -1 | awk '{printf $2}');
       if [ "$mountPoint" ] && [ "$mountPoint" != "/dev" ]; then
-        sudo umount -R $mountPoint;
-        sudo cryptsetup close ${cryptfsName};
+        umount -R $mountPoint;
+        cryptsetup close ${cryptfsName};
       else
-        sudo cryptsetup close ${cryptfsName};
+        cryptsetup close ${cryptfsName};
       fi
     else
       echo "Given devices isn't opened crypt device or it was closed before";
@@ -120,7 +124,7 @@ function close() {
 function create() {
   if [ $# -lt 1 ]; then help; exit 1;
   else
-    sudo cryptsetup -y -v luksFormat $1;
+    cryptsetup -y -v luksFormat $1;
   fi
 }
 
@@ -129,17 +133,29 @@ function set_ownership(){
   else
     mountPoint=$(list | grep "$USER" | grep "$1" | awk '{printf $3}')
     owner=$(stat -c %u $mountPoint);
-    if [ $owner -eq $UID ]; then 
-      if id $USER | grep -q $UID; then
+    if [ $owner -eq $RUID ]; then 
+      if id $USER | grep -q $RUID; then
         echo "User $USER is already owner of $mountPoint";
       fi
     else
-      sudo chown ${USER}:${USER} $mountPoint;
+      chown ${USER}:${USER} $mountPoint;
     fi
   fi
 }
 
 if [ "$1" ]; then
+
+  if [ $UID -ne 0 ]; then
+    echo "Permission denied!";
+    help;
+    exit 1;
+  fi
+ 
+  immudexCryptPID=$$;
+  parentProcessPID=$((immudexCryptPID - 1));
+  #immudex-crypt RUID is EUID of sudo, which spawning immudex-crypt
+  export RUID=$(grep '^Uid:' /proc/${parentProcessPID}/status | awk '{printf $2}');
+  export USER=$(grep "$RUID" /etc/passwd | cut -d ":" -f1);
 
   case $1 in
     "list") list;;
